#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2024.2.1.1"

# Which extra RobotPy components should be installed
# -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    # "all"
    # "apriltag"
    # "commands2"
    # "cscore"
    # "navx"
    # "pathplannerlib"
    # "phoenix5"
    # "phoenix6"
    # "playingwithfusion"
    # "rev" # this rev is newest version (2024.2.0) that does not work currently
    # "romi"
    # "sim"
    # "xrp"
]

# Other pip packages to install

requires = ["robotpy-rev==2024.0.0b1.post1"] # 2024.0.0b1.post1 is newest version that does not crash (its just the version right before 2024.2.0)
